# Generated by Django 3.0.7 on 2020-06-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KirrURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=220)),
                ('shortcode', models.CharField(blank=True, max_length=20, unique=True)),
                ('updated', models.DateTimeField(auto_now=True, unique=True)),
                ('Timestamp', models.DateTimeField(auto_now=True, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
