# Generated by Django 3.0.7 on 2020-06-26 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default=2, max_length=15),
            preserve_default=False,
        ),
    ]
