# Generated by Django 3.0.7 on 2020-06-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_kirrurl_shortcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kirrurl',
            name='shortcode',
        ),
    ]
