# Generated by Django 3.0.7 on 2020-06-26 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0003_remove_kirrurl_shortcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='kirrurl',
            name='shortcode',
            field=models.CharField(default='trydefaultshortcode', max_length=20),
            preserve_default=False,
        ),
    ]
